import { supabase } from '@/lib/supabaseClient';
import { hashHandoff, LEDGER_GENESIS_HASH, type LedgerEntry } from '@/lib/ledger-core';

export { canonicalHandoffPayload, hashHandoff, LEDGER_GENESIS_HASH, verifyLedgerEntries } from '@/lib/ledger-core';

export type HandoffStage = 'harvest' | 'aggregation' | 'logistics' | 'retail';
export type RecordHandoffInput = {
  batchId: string;
  stage: HandoffStage;
  location?: string;
  notes?: string;
  assignedDistributorName?: string;
  assignedRetailerName?: string;
  quantityKg?: number;
};

type StoredHandoff = {
  id: string; batch_id: string; handler_id: string; stage: HandoffStage; location: string | null; notes: string | null;
  created_at: string; prev_hash: string | null; current_hash: string | null; ledger_version: number;
};

/**
 * Simulates a blockchain hash for a supply chain stage.
 * In a real blockchain, this would involve signing and consensus.
 */
/** @deprecated Use recordHandoff. Hashes must be generated by the database RPC. */
export function generateHash(data: object, prevHash = LEDGER_GENESIS_HASH): string {
  return hashHandoff({ batchId: '', actorId: '', stage: '', location: '', notes: JSON.stringify(data), createdAt: '', prevHash });
}

/**
 * Formats a hash for display (shortened)
 */
export function formatHash(hash: string): string {
  if (!hash) return '';
  return `${hash.substring(0, 8)}...${hash.substring(hash.length - 8)}`;
}

/**
 * Integration point for a future Polygon signer. Returning null keeps batch
 * creation fully functional when no blockchain wallet/RPC is configured.
 */
export async function recordBatchOnPolygon(_dataHash: string): Promise<string | null> {
  void _dataHash;
  return null;
}

export async function getAuthenticatedActor() {
  const { data: { user }, error } = await supabase.auth.getUser();
  if (error || !user) throw new Error('Please sign in before recording a supply-chain update.');
  return user;
}

/**
 * The database derives actor, timestamp, previous hash and SHA-256 hash. Clients
 * provide only the business facts needed to append a handoff.
 */
export async function recordHandoff(input: RecordHandoffInput) {
  await getAuthenticatedActor();
  const { data, error } = await supabase.rpc('record_batch_handoff', {
    p_batch_id: input.batchId,
    p_stage: input.stage,
    p_location: input.location ?? null,
    p_notes: input.notes ?? null,
    p_assigned_distributor_name: input.assignedDistributorName ?? null,
    p_assigned_retailer_name: input.assignedRetailerName ?? null,
    p_quantity_kg: input.quantityKg ?? null,
  });
  if (error) throw new Error(error.message);
  return Array.isArray(data) ? data[0] : data;
}

/** Verify only modern (ledger_version = 1) records; legacy rows remain explicitly unverified. */
export async function verifyBatchLedger(batchId: string) {
  const { count: totalCount, error: countError } = await supabase.from('batch_handoffs').select('*', { count: 'exact', head: true }).eq('batch_id', batchId);
  if (countError) throw new Error(countError.message);
  const { data, error } = await supabase.from('batch_handoffs')
    .select('id, batch_id, handler_id, stage, location, notes, created_at, prev_hash, current_hash, ledger_version')
    .eq('batch_id', batchId).eq('ledger_version', 1).order('created_at', { ascending: true }).order('id', { ascending: true });
  if (error) throw new Error(error.message);
  const entries: LedgerEntry[] = ((data ?? []) as StoredHandoff[]).map((handoff) => ({
    batchId: handoff.batch_id, actorId: handoff.handler_id, stage: handoff.stage,
    location: handoff.location ?? '', notes: handoff.notes ?? '',
    createdAt: new Date(handoff.created_at).toISOString(), prevHash: handoff.prev_hash ?? '', currentHash: handoff.current_hash ?? '',
  }));
  const verification = (await import('@/lib/ledger-core')).verifyLedgerEntries(entries);
  return { ...verification, legacyHandoffCount: Math.max(0, (totalCount ?? 0) - entries.length) };
}
