import { supabase } from '@/lib/supabaseClient';
import { hashHandoff, LEDGER_GENESIS_HASH, type LedgerEntry } from '@/lib/ledger-core';

export { canonicalHandoffPayload, hashHandoff, LEDGER_GENESIS_HASH, verifyLedgerEntries } from '@/lib/ledger-core';

export type HandoffStage = 'harvest' | 'aggregation' | 'logistics' | 'retail';
export type RecordHandoffInput = {
  batchId: string;
  stage: HandoffStage;
  location?: string;
  notes?: string;
  assignedDistributorName?: string;
  assignedRetailerName?: string;
  quantityKg?: number;
};

<<<<<<< HEAD
=======
export type HandoffBlockchainStatus = 'VERIFIED' | 'NOT_ANCHORED' | 'TAMPERED';

export type HandoffAnchor = {
  id?: string;
  handoff_id: string;
  tx_hash: string;
  committed_hash: string;
  network?: string | null;
  created_at?: string;
};

export type HandoffRecord = {
  id: string;
  batch_id?: string;
  handler_id?: string | null;
  stage: string;
  location?: string | null;
  notes?: string | null;
  assigned_distributor_name?: string | null;
  assigned_retailer_name?: string | null;
  quantity_kg?: number | null;
  created_at: string;
  prev_hash?: string | null;
  current_hash?: string | null;
  ledger_version?: number;
  actor_profile?: { full_name: string; location: string | null; role: string } | null;
};

export type HandoffVerificationResult = {
  status: HandoffBlockchainStatus;
  headline: string;
  message: string;
  isAnchored: boolean;
  isTampered: boolean;
  isVerified: boolean;
  recordedHash: string | null;
  committedHash: string | null;
  txHash: string | null;
  network: string;
  polygonScanUrl: string | null;
};

export type VerifiedHandoff = HandoffRecord & {
  anchor?: HandoffAnchor | null;
  verification: HandoffVerificationResult;
};

export type BatchBlockchainStatus = 'VERIFIED' | 'NOT_ANCHORED' | 'NOT_FULLY_ANCHORED' | 'TAMPERED';

export type BatchVerificationSummary = {
  status: BatchBlockchainStatus;
  badgeLabel: string;
  headline: string;
  description: string;
  consumerDescription: string;
  tamperedStages: string[];
  unanchoredStages: string[];
  verifiedStages: string[];
  totalHandoffs: number;
  verifiedCount: number;
  unanchoredCount: number;
  tamperedCount: number;
  handoffs: VerifiedHandoff[];
  hasTampered: boolean;
  isFullyVerified: boolean;
};

>>>>>>> 9affdaf (flowchart)
type StoredHandoff = {
  id: string; batch_id: string; handler_id: string; stage: HandoffStage; location: string | null; notes: string | null;
  created_at: string; prev_hash: string | null; current_hash: string | null; ledger_version: number;
};

/**
 * Simulates a blockchain hash for a supply chain stage.
 * In a real blockchain, this would involve signing and consensus.
 */
/** @deprecated Use recordHandoff. Hashes must be generated by the database RPC. */
export function generateHash(data: object, prevHash = LEDGER_GENESIS_HASH): string {
  return hashHandoff({ batchId: '', actorId: '', stage: '', location: '', notes: JSON.stringify(data), createdAt: '', prevHash });
}

/**
 * Formats a hash for display (shortened)
 */
export function formatHash(hash: string): string {
  if (!hash) return '';
  return `${hash.substring(0, 8)}...${hash.substring(hash.length - 8)}`;
}

/** Client-side handoffs are anchored through the protected Next.js API route. */
export async function recordBatchOnPolygon(dataHash: string): Promise<string | null> {
  const response = await fetch('/api/blockchain/anchor', {
    method: 'POST',
    headers: { 'content-type': 'application/json' },
    body: JSON.stringify({ handoffId: null, dataHash }),
  });
  if (!response.ok) {
    const body = await response.json().catch(() => null) as { error?: string } | null;
    throw new Error(body?.error || 'Could not anchor this hash on Polygon.');
  }
  const body = await response.json() as { txHash?: string | null };
  return body.txHash ?? null;
}

export async function getAuthenticatedActor() {
  const { data: { user }, error } = await supabase.auth.getUser();
  if (error || !user) throw new Error('Please sign in before recording a supply-chain update.');
  return user;
}

/**
 * The database derives actor, timestamp, previous hash and SHA-256 hash. Clients
 * provide only the business facts needed to append a handoff.
 */
export async function recordHandoff(input: RecordHandoffInput) {
  await getAuthenticatedActor();
  const { data, error } = await supabase.rpc('record_batch_handoff', {
    p_batch_id: input.batchId,
    p_stage: input.stage,
    p_location: input.location ?? null,
    p_notes: input.notes ?? null,
    p_assigned_distributor_name: input.assignedDistributorName ?? null,
    p_assigned_retailer_name: input.assignedRetailerName ?? null,
    p_quantity_kg: input.quantityKg ?? null,
  });
  if (error) throw new Error(error.message);
  const handoff = Array.isArray(data) ? data[0] : data;
  if (handoff?.id && handoff?.current_hash && process.env.NEXT_PUBLIC_POLYGON_ANCHORING !== 'disabled') {
    try {
      const response = await fetch('/api/blockchain/anchor', {
        method: 'POST',
        headers: { 'content-type': 'application/json' },
        body: JSON.stringify({ handoffId: handoff.id, dataHash: handoff.current_hash }),
      });
      if (!response.ok) {
        const body = await response.json().catch(() => null) as { error?: string } | null;
        throw new Error(body?.error || 'Could not anchor the handoff hash on Polygon.');
      }
      const body = await response.json() as { txHash?: string | null };
      if (body.txHash) {
        const { error: anchorError } = await supabase.from('handoff_blockchain_anchors').insert({
          handoff_id: handoff.id,
          tx_hash: body.txHash,
          committed_hash: handoff.current_hash,
          network: 'polygon-amoy',
        });
        if (anchorError) throw new Error(anchorError.message);
      }
    } catch (anchorError) {
      throw anchorError instanceof Error ? anchorError : new Error('Blockchain anchoring failed.');
    }
  }
  return handoff;
}

/** Verify only modern (ledger_version = 1) records; legacy rows remain explicitly unverified. */
export async function verifyBatchLedger(batchId: string) {
  const { count: totalCount, error: countError } = await supabase.from('batch_handoffs').select('*', { count: 'exact', head: true }).eq('batch_id', batchId);
  if (countError) throw new Error(countError.message);
  const { data, error } = await supabase.from('batch_handoffs')
    .select('id, batch_id, handler_id, stage, location, notes, created_at, prev_hash, current_hash, ledger_version')
    .eq('batch_id', batchId).eq('ledger_version', 1).order('created_at', { ascending: true }).order('id', { ascending: true });
  if (error) throw new Error(error.message);
  const entries: LedgerEntry[] = ((data ?? []) as StoredHandoff[]).map((handoff) => ({
    batchId: handoff.batch_id, actorId: handoff.handler_id, stage: handoff.stage,
    location: handoff.location ?? '', notes: handoff.notes ?? '',
    createdAt: new Date(handoff.created_at).toISOString(), prevHash: handoff.prev_hash ?? '', currentHash: handoff.current_hash ?? '',
  }));
  const verification = (await import('@/lib/ledger-core')).verifyLedgerEntries(entries);
  return { ...verification, legacyHandoffCount: Math.max(0, (totalCount ?? 0) - entries.length) };
}
