import Link from 'next/link';
import { AlertTriangle, Calendar, FlaskConical, MapPin, Scale, ShieldCheck } from 'lucide-react';
import { getBatchByCode } from '@/lib/batchActions';

export default async function TracePage({ params }: { params: Promise<{ batchId: string }> }) {
  const { batchId } = await params;
  let batch = null;
  try { batch = await getBatchByCode(batchId); } catch { /* unavailable configuration is rendered as not found */ }
  if (!batch) return <main className="flex min-h-screen flex-col items-center justify-center bg-slate-50 p-6 text-center"><AlertTriangle className="mb-4 h-14 w-14 text-amber-500" /><h1 className="text-2xl font-bold">Batch not found</h1><p className="mt-2 text-slate-600">This trace record is unavailable or its Batch ID is incorrect.</p><Link href="/" className="mt-6 font-semibold text-green-700">Return to tracking</Link></main>;
  const recalled = batch.status === 'CONTAMINATED_RECALLED';
  const labStatus = batch.lab_tests?.[0]?.test_status ?? batch.pesticide_status ?? 'PENDING';
  return <main className="min-h-screen bg-slate-50 pb-10"><header className="bg-green-700 p-4 text-white"><Link href="/" className="mx-auto block max-w-4xl text-xl font-bold">SurakshaKhadya</Link></header><section className={`p-4 text-center font-bold ${recalled ? 'bg-red-600 text-white' : 'bg-green-100 text-green-900'}`}>{recalled ? '⚠️ DO NOT CONSUME — FSSAI RECALL ALERT' : '✓ FSSAI Verified Safe'}</section><div className="mx-auto max-w-4xl space-y-6 p-4 md:p-6"><div className="rounded-xl border border-slate-200 bg-white p-6"><p className="font-mono text-sm text-slate-500">{batch.batch_code}</p><h1 className="mt-1 text-3xl font-bold">{batch.crop_name}</h1></div><div className="rounded-xl border border-green-200 bg-green-50 p-5"><div className="flex items-center gap-2 font-bold text-green-900"><ShieldCheck /> Blockchain verification</div><p className="mt-3 text-sm">Status: <b>{batch.status}</b></p><p className="mt-1 break-all font-mono text-xs text-slate-600">Batch hash: {batch.data_hash || 'Pending verification'}</p>{batch.polygon_tx_hash && <a className="mt-3 inline-block rounded-full bg-purple-700 px-3 py-1 font-semibold text-white" href={`https://amoy.polygonscan.com/tx/${batch.polygon_tx_hash}`} target="_blank" rel="noreferrer">Verified on Polygon</a>}</div><div className="grid gap-4 sm:grid-cols-2"><Info icon={<FlaskConical />} label="Pesticide lab status" value={labStatus} /><Info icon={<Scale />} label="Weight" value={`${batch.total_weight_kg} kg`} /><Info icon={<Calendar />} label="Harvest date" value={new Date(batch.harvest_date).toLocaleDateString()} /><Info icon={<MapPin />} label="Farm location" value={batch.farm_location} /></div></div></main>;
}
function Info({ icon, label, value }: { icon: React.ReactNode; label: string; value: string }) { return <div className="rounded-xl border border-slate-200 bg-white p-5"><div className="flex items-center gap-2 text-green-700">{icon}<span className="text-sm font-semibold">{label}</span></div><p className="mt-2 text-lg font-bold text-slate-900">{value}</p></div>; }
