'use client';

import { useState } from 'react';
import { AlertTriangle, Store } from 'lucide-react';
import { acceptBatchByRetailer } from '@/lib/batchActions';
import { supabase } from '@/lib/supabaseClient';
import { getAuthenticatedActor } from '@/lib/blockchain';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { PortalShell } from '@/components/portal-shell';

export default function RetailerPage() {
  const [batchCode, setBatchCode] = useState(''); const [location, setLocation] = useState(''); const [recallCode, setRecallCode] = useState(''); const [reason, setReason] = useState(''); const [loading, setLoading] = useState(false); const [message, setMessage] = useState<{ type: 'success' | 'error'; text: string } | null>(null);
  async function find(code: string) { const { data, error } = await supabase.from('batches').select('id').eq('batch_code', code).single(); if (error || !data) throw new Error('Batch not found.'); return data; }
  async function accept(event: React.FormEvent) { event.preventDefault(); setLoading(true); setMessage(null); try { const result = await acceptBatchByRetailer({ batchCode, storeLocation: location }); if (!result.success) { setMessage({ type: 'error', text: result.error }); return; } setMessage({ type: 'success', text: 'Batch successfully received on store shelf!' }); setBatchCode(''); setLocation(''); } catch (error) { setMessage({ type: 'error', text: error instanceof Error ? error.message : 'Could not accept batch.' }); } finally { setLoading(false); } }
  async function recall(event: React.FormEvent) { event.preventDefault(); try { const user = await getAuthenticatedActor(); const batch = await find(recallCode); const { error } = await supabase.from('batches').update({ status: 'recalled', is_recalled: true }).eq('id', batch.id); if (error) throw error; const { error: auditError } = await supabase.from('batch_handoffs').insert({ batch_id: batch.id, handler_id: user.id, stage: 'retail', notes: `RECALL: ${reason}` }); if (auditError) throw auditError; setMessage({ type: 'success', text: `Recall initiated for ${recallCode}.` }); setRecallCode(''); setReason(''); } catch (error) { setMessage({ type: 'error', text: error instanceof Error ? error.message : 'Could not initiate recall.' }); } }
  return <PortalShell title="Retailer store" description="Accept delivered batches or start a safety recall." icon={Store}>{message && <p role="alert" className={`mb-5 rounded-lg border p-3 ${message.type === 'success' ? 'border-green-200 bg-green-50 text-green-800' : 'border-red-200 bg-red-50 text-red-800'}`}>{message.text}</p>}<div className="grid gap-6 md:grid-cols-2"><Card className="portal-surface"><CardHeader><CardTitle>Store shelf acceptance</CardTitle></CardHeader><CardContent><form onSubmit={accept} className="space-y-4"><div><Label htmlFor="batch">Batch ID</Label><Input id="batch" value={batchCode} onChange={(event) => setBatchCode(event.target.value)} required /></div><div><Label htmlFor="location">Store name / location</Label><Input id="location" value={location} onChange={(event) => setLocation(event.target.value)} required /></div><Button type="submit" disabled={loading} className="portal-action w-full py-4 text-lg font-bold">{loading ? 'Processing...' : 'Accept batch'}</Button></form></CardContent></Card><Card className="border border-red-200"><CardHeader><CardTitle className="text-red-700">Contamination recall</CardTitle></CardHeader><CardContent><form onSubmit={recall} className="space-y-4"><div><Label htmlFor="recall">Batch ID</Label><Input id="recall" value={recallCode} onChange={(event) => setRecallCode(event.target.value)} required /></div><div><Label htmlFor="reason">Recall reason</Label><Input id="reason" value={reason} onChange={(event) => setReason(event.target.value)} required /></div><Button type="submit" variant="destructive" className="w-full py-4 text-lg font-bold"><AlertTriangle className="mr-2" />Trigger recall</Button></form></CardContent></Card></div></PortalShell>;
}
