`'use client';

import { useEffect, useMemo, useState } from 'react';
import { AlertTriangle, CheckCircle2, CircleDollarSign, Package, ShoppingCart, Store, Truck } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { PortalShell } from '@/components/portal-shell';
import { retailerDemoDeliveries, retailerDemoSales, retailerDemoStock, type RetailerDelivery, type Sale, type StockItem, type StockStatus } from '@/lib/retailer-demo-data';

const storageKey = 'surakshakhadya-retailer-simple-v1';
type ReceiptEvent = { batchId: string; event: string; timestamp: string };
type RetailerState = { deliveries: RetailerDelivery[]; stock: StockItem[]; receiptEvents?: ReceiptEvent[]; safetyAlertRemoved?: boolean };

function initialState(): RetailerState {
  if (typeof window === 'undefined') return { deliveries: retailerDemoDeliveries, stock: retailerDemoStock };
  try { const saved = window.localStorage.getItem(storageKey); return saved ? JSON.parse(saved) as RetailerState : { deliveries: retailerDemoDeliveries, stock: retailerDemoStock }; }
  catch { return { deliveries: retailerDemoDeliveries, stock: retailerDemoStock }; }
}

export default function RetailerDashboard() {
  const [data, setData] = useState<RetailerState>(initialState);
  const [activeDeliveryId, setActiveDeliveryId] = useState<string | null>(null);
  const [flow, setFlow] = useState<'home' | 'confirm' | 'problem' | 'done'>('home');
  const [problem, setProblem] = useState('');
  const [purchase, setPurchase] = useState<RetailerDelivery | null>(null);
  useEffect(() => { window.localStorage.setItem(storageKey, JSON.stringify(data)); }, [data]);
  useEffect(() => {
    const sync = (event: StorageEvent) => { if (event.key === storageKey) setData(initialState()); };
    window.addEventListener('storage', sync);
    return () => window.removeEventListener('storage', sync);
  }, []);
  const waiting = data.deliveries.find((delivery) => delivery.status === 'WAITING');
  const active = data.deliveries.find((delivery) => delivery.id === activeDeliveryId) ?? waiting;
  const purchases = useMemo(() => data.deliveries.filter((delivery) => delivery.status !== 'WAITING'), [data.deliveries]);
  const scrollTo = (id: string) => document.getElementById(id)?.scrollIntoView({ behavior: 'smooth', block: 'start' });
  const openDelivery = (delivery: RetailerDelivery, next: 'confirm' | 'problem') => { setActiveDeliveryId(delivery.id); setProblem(''); setFlow(next); };
  const confirmReceipt = () => {
    if (!active || active.status !== 'WAITING') return;
    const timestamp = '25 Aug 2026, 10:30';
    setData((current) => ({
      ...current,
      deliveries: current.deliveries.map((delivery) => delivery.id === active.id ? { ...delivery, status: 'RECEIVED', receivedAt: timestamp } : delivery),
      stock: current.stock.map((item) => item.product === active.product ? { ...item, quantity: item.quantity + active.quantity, batchId: active.batchId, status: 'AVAILABLE' } : item),
      receiptEvents: [{ batchId: active.batchId, event: 'Retailer receipt confirmed', timestamp }, ...(current.receiptEvents ?? [])],
    }));
    setFlow('done');
  };
  const reportProblem = () => {
    if (!active || !problem || active.status !== 'WAITING') return;
    setData((current) => ({ ...current, deliveries: current.deliveries.map((delivery) => delivery.id === active.id ? { ...delivery, status: 'ISSUE REPORTED', issue: problem } : delivery), receiptEvents: [{ batchId: active.batchId, event: `Problem reported: ${problem}`, timestamp: '25 Aug 2026, 10:30' }, ...(current.receiptEvents ?? [])] }));
    setFlow('done');
  };
  const removeAffectedStock = () => setData((current) => ({ ...current, stock: current.stock.map((item) => item.batchId === 'SK-2026-003' ? { ...item, status: 'BLOCKED' } : item), safetyAlertRemoved: true }));
  return <PortalShell title="Retailer Dashboard" description="Manage your stock and orders easily." icon={Store}>
    <section className="grid grid-cols-2 gap-3 sm:grid-cols-4"><Summary icon={Package} title="My Stock" value={`${data.stock.reduce((total, item) => total + item.quantity, 0)} kg`} onClick={() => scrollTo('stock')} /><Summary icon={Truck} title="New Delivery" value={waiting ? '1 waiting' : 'No new deliveries'} tone={waiting ? 'amber' : 'green'} onClick={() => waiting ? openDelivery(waiting, 'confirm') : scrollTo('purchases')} /><Summary icon={ShoppingCart} title="Purchases" value={`${purchases.length} received`} onClick={() => scrollTo('purchases')} /><Summary icon={CircleDollarSign} title="Sales" value={`${retailerDemoSales.length} recent`} onClick={() => scrollTo('sales')} /></section>
    <section className="mt-6">{waiting ? <NewDelivery delivery={waiting} onConfirm={() => openDelivery(waiting, 'confirm')} onProblem={() => openDelivery(waiting, 'problem')} /> : <NoDelivery />}</section>
    {!data.safetyAlertRemoved && <SafetyAlert onRemove={removeAffectedStock} onView={() => scrollTo('stock')} />}
    <Section id="stock" title="My Stock" description="Products in your shop." icon={Package}><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{data.stock.map((item) => <StockCard key={`${item.product}-${item.batchId}`} item={item} />)}</div></Section>
    <Section id="purchases" title="My Purchases" description="Goods received from distributors." icon={ShoppingCart}><div className="grid gap-3 md:grid-cols-2">{purchases.map((item) => <PurchaseCard key={item.id} item={item} onClick={() => setPurchase(item)} />)}</div>{!purchases.length && <Empty text="Your received deliveries will appear here." />}</Section>
    <Section id="sales" title="My Sales" description="Your recent sales." icon={CircleDollarSign}><div className="grid gap-3 md:grid-cols-3">{retailerDemoSales.map((sale) => <SaleCard key={sale.id} sale={sale} />)}</div></Section>
    <DeliveryDialog open={flow !== 'home'} flow={flow} delivery={active ?? null} problem={problem} onProblem={setProblem} onConfirm={confirmReceipt} onReport={reportProblem} onClose={() => { setFlow('home'); setActiveDeliveryId(null); setProblem(''); }} />
    <PurchaseDialog purchase={purchase} onClose={() => setPurchase(null)} />
  </PortalShell>;
}

function Summary({ icon: Icon, title, value, tone = 'green', onClick }: { icon: typeof Package; title: string; value: string; tone?: 'green' | 'amber'; onClick: () => void }) { const colour = tone === 'amber' ? 'bg-amber-100 text-amber-700' : 'bg-green-100 text-green-700'; return <button onClick={onClick} className="text-left"><Card className="portal-surface h-full transition-transform hover:-translate-y-0.5 hover:shadow-xl"><CardContent className="flex min-h-30 flex-col justify-between gap-3"><div className={`w-fit rounded-xl p-3 ${colour}`}><Icon className="h-6 w-6" /></div><div><p className="text-base font-bold text-slate-900 sm:text-lg">{title}</p><p className="mt-0.5 text-sm text-slate-600">{value}</p></div></CardContent></Card></button>; }
function NewDelivery({ delivery, onConfirm, onProblem }: { delivery: RetailerDelivery; onConfirm: () => void; onProblem: () => void }) { return <Card className="border border-amber-200 bg-amber-50 shadow-lg"><CardContent className="p-5 sm:p-6"><div className="flex flex-col gap-5 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-start gap-3"><div className="rounded-xl bg-amber-100 p-3 text-amber-700"><Truck className="h-7 w-7" /></div><div><p className="font-bold tracking-wide text-amber-800">NEW DELIVERY</p><p className="mt-1 text-lg font-bold text-slate-900">{delivery.emoji} {delivery.product} · {delivery.quantity} kg</p><p className="text-sm text-slate-600">From: {delivery.distributor}</p><p className="mt-1 text-xs text-slate-500">Batch: {delivery.batchId}</p></div></div><div className="w-full space-y-2 sm:max-w-xs"><p className="text-sm font-medium text-slate-700">Please confirm that you received this delivery.</p><Button size="lg" className="portal-action h-11 w-full text-base" onClick={onConfirm}><CheckCircle2 />YES, I RECEIVED IT</Button><Button size="lg" variant="outline" className="h-11 w-full border-amber-300 bg-white text-amber-800 hover:bg-amber-100" onClick={onProblem}><AlertTriangle />REPORT A PROBLEM</Button></div></div></CardContent></Card>; }
function NoDelivery() { return <Card className="portal-surface"><CardContent className="flex items-center gap-3 py-5"><div className="rounded-xl bg-green-100 p-3 text-green-700"><CheckCircle2 className="h-6 w-6" /></div><div><p className="font-bold text-slate-900">No new deliveries</p><p className="text-sm text-slate-600">You are all caught up.</p></div></CardContent></Card>; }
function SafetyAlert({ onView, onRemove }: { onView: () => void; onRemove: () => void }) { return <Card className="mt-6 border border-red-200 bg-red-50 shadow-lg"><CardContent className="flex flex-col gap-4 p-5 sm:flex-row sm:items-center sm:justify-between"><div className="flex gap-3"><div className="h-fit rounded-xl bg-red-100 p-3 text-red-700"><AlertTriangle className="h-6 w-6" /></div><div><p className="font-bold text-red-800">FOOD SAFETY ALERT</p><p className="mt-1 font-semibold text-slate-900">Spinach · Batch SK-2026-003</p><p className="text-sm text-red-700">This product has been flagged. Please do not sell this batch.</p></div></div><div className="flex gap-2"><Button variant="outline" className="border-red-200 bg-white text-red-700 hover:bg-red-100" onClick={onView}>VIEW DETAILS</Button><Button variant="destructive" onClick={onRemove}>MARK AS REMOVED</Button></div></CardContent></Card>; }
function Section({ id, title, description, icon: Icon, children }: { id: string; title: string; description: string; icon: typeof Package; children: React.ReactNode }) { return <section id={id} className="mt-8 scroll-mt-6"><div className="mb-4 flex items-center gap-3"><div className="rounded-xl bg-green-100 p-3 text-green-700"><Icon className="h-5 w-5" /></div><div><h2 className="text-xl font-bold text-slate-900">{title}</h2><p className="text-sm text-slate-600">{description}</p></div></div>{children}</section>; }
function StockCard({ item }: { item: StockItem }) { const styles: Record<StockStatus, string> = { AVAILABLE: 'text-green-700', 'LOW STOCK': 'text-amber-700', 'OUT OF STOCK': 'text-red-700', BLOCKED: 'text-red-700' }; const dots: Record<StockStatus, string> = { AVAILABLE: '🟢', 'LOW STOCK': '🟡', 'OUT OF STOCK': '🔴', BLOCKED: '🔴' }; return <Card className="portal-surface"><CardContent className="p-5"><p className="text-3xl" aria-hidden>{item.emoji}</p><p className="mt-3 text-lg font-bold text-slate-900">{item.product}</p><p className="mt-1 text-xl font-semibold text-slate-800">{item.quantity} kg</p><p className="mt-2 text-xs text-slate-500">Batch {item.batchId}</p><p className={`mt-3 text-sm font-semibold ${styles[item.status]}`}>{dots[item.status]} {item.status.charAt(0) + item.status.slice(1).toLowerCase()}</p></CardContent></Card>; }
function PurchaseCard({ item, onClick }: { item: RetailerDelivery; onClick: () => void }) { const received = item.status === 'RECEIVED'; return <button onClick={onClick} className="text-left"><Card className="portal-surface h-full transition-transform hover:-translate-y-0.5 hover:shadow-xl"><CardContent className="flex items-center justify-between gap-3 p-5"><div><p className="font-mono text-xs text-slate-500">PUR-{item.id.replace('delivery-', '')}</p><p className="mt-1 text-lg font-bold text-slate-900">{item.emoji} {item.product} · {item.quantity} kg</p><p className="mt-1 text-sm text-slate-600">{item.distributor}</p><p className="mt-1 text-sm font-medium text-slate-700">₹{item.amount.toLocaleString('en-IN')} · {item.batchId}</p><p className="mt-2 text-xs text-slate-500">{item.receivedAt ?? item.date}</p></div><span className={`shrink-0 text-sm font-semibold ${received ? 'text-green-700' : 'text-red-700'}`}>{received ? '✓ Received' : '⚠ Reported'}</span></CardContent></Card></button>; }
function SaleCard({ sale }: { sale: Sale }) { return <Card className="portal-surface"><CardContent className="p-5"><p className="font-mono text-xs text-slate-500">SAL-{sale.id.replace('sale-', '')}</p><p className="mt-1 text-lg font-bold text-slate-900">{sale.emoji} {sale.product}</p><p className="mt-1 text-sm text-slate-600">{sale.quantity} kg sold</p><p className="mt-2 text-lg font-semibold text-slate-800">₹{sale.amount}</p><p className="mt-1 text-xs text-slate-500">{sale.date} · Batch {sale.batchId}</p></CardContent></Card>; }
function Empty({ text }: { text: string }) { return <Card className="portal-surface"><CardContent className="py-6 text-center text-slate-600">{text}</CardContent></Card>; }

function DeliveryDialog({ open, flow, delivery, problem, onProblem, onConfirm, onReport, onClose }: { open: boolean; flow: 'home' | 'confirm' | 'problem' | 'done'; delivery: RetailerDelivery | null; problem: string; onProblem: (value: string) => void; onConfirm: () => void; onReport: () => void; onClose: () => void }) { if (!delivery) return null; const isProblem = flow === 'problem'; const done = flow === 'done'; return <Dialog open={open} onOpenChange={(isOpen) => !isOpen && onClose()}><DialogContent className="max-w-md p-6"><DialogHeader><DialogTitle className="text-xl">{done ? '✓ Delivery received' : isProblem ? 'What is wrong?' : 'Confirm delivery?'}</DialogTitle><DialogDescription>{done ? (problem ? 'Your distributor has been notified.' : 'Your stock has been updated.') : isProblem ? 'Choose one option.' : 'Please check the delivery once.'}</DialogDescription></DialogHeader>{done ? <Button size="lg" className="portal-action h-11 w-full text-base" onClick={onClose}>OK</Button> : isProblem ? <div className="space-y-3">{['Quantity is wrong', 'Product is damaged', 'Wrong product', 'Other'].map((option) => <button key={option} onClick={() => onProblem(option)} className={`w-full rounded-xl border p-4 text-left text-base font-semibold ${problem === option ? 'border-amber-400 bg-amber-50 text-amber-900' : 'border-slate-200 bg-white text-slate-700 hover:bg-slate-50'}`}>{option}</button>)}<Button size="lg" variant="destructive" disabled={!problem} className="mt-2 h-11 w-full text-base" onClick={onReport}>SEND REPORT</Button></div> : <div className="space-y-5"><div className="rounded-xl bg-green-50 p-4"><p className="text-xl font-bold text-slate-900">{delivery.emoji} {delivery.product} — {delivery.quantity} kg</p><p className="mt-2 text-sm text-slate-700">From:</p><p className="font-semibold text-slate-900">{delivery.distributor}</p></div><div className="flex gap-2"><Button size="lg" variant="outline" className="h-11 flex-1" onClick={onClose}>CANCEL</Button><Button size="lg" className="portal-action h-11 flex-1 text-base" onClick={onConfirm}>CONFIRM RECEIPT</Button></div></div>}</DialogContent></Dialog>; }
function PurchaseDialog({ purchase, onClose }: { purchase: RetailerDelivery | null; onClose: () => void }) { if (!purchase) return null; return <Dialog open={Boolean(purchase)} onOpenChange={(open) => !open && onClose()}><DialogContent className="max-w-md p-6"><DialogHeader><DialogTitle className="text-xl">Batch Details</DialogTitle><DialogDescription>Simple purchase information.</DialogDescription></DialogHeader><div className="grid gap-3 rounded-xl bg-slate-50 p-4 text-sm"><Detail label="Purchase ID" value={`PUR-${purchase.id.replace('delivery-', '')}`} /><Detail label="Product" value={purchase.product} /><Detail label="Quantity" value={`${purchase.quantity} kg`} /><Detail label="From" value={purchase.distributor} /><Detail label="Batch ID" value={purchase.batchId} /><Detail label="Status" value={purchase.status === 'RECEIVED' ? 'Received' : 'Problem reported'} /></div></DialogContent></Dialog>; }
function Detail({ label, value }: { label: string; value: string }) { return <div className="flex items-center justify-between gap-4"><span className="text-slate-500">{label}</span><span className="text-right font-semibold text-slate-800">{value}</span></div>; }
