'use client';
/* eslint-disable @next/next/no-img-element */
import { FormEvent, useState } from 'react';
import Link from 'next/link';
import { createBatch, type BatchRecord } from '@/lib/batchActions';
import { supabase } from '@/lib/supabaseClient';

const today = new Date().toISOString().slice(0, 10);
export function CreateBatchForm() {
  const [cropName, setCropName] = useState(''); const [weight, setWeight] = useState(''); const [harvestDate, setHarvestDate] = useState(today); const [farmLocation, setFarmLocation] = useState(''); const [batch, setBatch] = useState<BatchRecord | null>(null); const [error, setError] = useState(''); const [loading, setLoading] = useState(false);
  async function handleSubmit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setError(''); setLoading(true); try { const { data: { user } } = await supabase.auth.getUser(); if (!user) throw new Error('Please sign in as a farmer first.'); setBatch(await createBatch({ farmerId: user.id, cropName, totalWeightKg: Number(weight), harvestDate, farmLocation })); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Could not save batch.'); } finally { setLoading(false); } }
  if (batch) return <div className="portal-surface space-y-5 p-6 text-center"><h2 className="text-2xl font-bold text-green-800">Batch saved successfully</h2><img src={batch.qr_code_url} alt={`QR code for ${batch.batch_code}`} className="mx-auto h-64 w-64 rounded-lg border bg-white p-2" /><p className="font-mono text-xl font-bold">{batch.batch_code}</p><div className="flex flex-col gap-3 sm:flex-row sm:justify-center"><button onClick={() => window.print()} className="portal-action rounded-lg px-5 py-3 font-bold">Download / Print QR</button><Link href={`/trace/${batch.batch_code}`} className="rounded-lg border border-green-700 px-5 py-3 font-bold text-green-700">Test public trace</Link></div></div>;
  return <form onSubmit={handleSubmit} className="portal-surface space-y-5 p-6"><h2 className="text-2xl font-bold text-slate-900">Register a harvest batch</h2>{error && <p className="rounded-lg border-2 border-red-500 bg-red-100 p-3 text-red-900">{error}</p>}<div><label className="font-semibold">Crop name</label><input className="portal-field mt-1 w-full rounded-lg p-3" value={cropName} onChange={(e) => setCropName(e.target.value)} required /></div><div className="flex flex-wrap gap-2">{[['Tomato','🍅'],['Potato','🥔'],['Onion','🧅'],['Wheat','🌾']].map(([name, emoji]) => <button key={name} type="button" onClick={() => setCropName(name)} className="rounded-lg border border-green-200 px-3 py-2 font-semibold hover:bg-green-50">{emoji} {name}</button>)}</div><div><label className="font-semibold">Weight (kg)</label><input type="number" min="0.01" step="0.01" className="portal-field mt-1 w-full rounded-lg p-3" value={weight} onChange={(e) => setWeight(e.target.value)} required /></div><div><label className="font-semibold">Harvest date</label><input type="date" className="portal-field mt-1 w-full rounded-lg p-3" value={harvestDate} onChange={(e) => setHarvestDate(e.target.value)} required /></div><div><label className="font-semibold">Farm location</label><input className="portal-field mt-1 w-full rounded-lg p-3" value={farmLocation} onChange={(e) => setFarmLocation(e.target.value)} required /></div><button type="submit" disabled={loading} className="portal-action w-full rounded-lg py-4 text-lg font-bold disabled:opacity-60">{loading ? 'Saving & Generating QR...' : 'Save & Get QR Code'}</button></form>;
}
