'use client';

import { CheckCircle2, ChevronDown, Clipboard, ExternalLink, TriangleAlert, XCircle } from 'lucide-react';
import type { BatchIntegrity, IntegrityHandoff, IntegrityStatus } from '@/lib/integrity';

const style: Record<IntegrityStatus, string> = { VERIFIED: 'border-green-200 bg-green-50 text-green-900', WARNING: 'border-amber-200 bg-amber-50 text-amber-950', BROKEN: 'border-red-200 bg-red-50 text-red-950' };
const label: Record<IntegrityStatus, string> = { VERIFIED: 'VERIFIED', WARNING: 'INTEGRITY WARNING', BROKEN: 'VERIFICATION FAILED' };
function Icon({ status }: { status: IntegrityStatus }) { return status === 'VERIFIED' ? <CheckCircle2 className="h-6 w-6 text-green-700" /> : status === 'WARNING' ? <TriangleAlert className="h-6 w-6 text-amber-600" /> : <XCircle className="h-6 w-6 text-red-700" />; }
function ShortHash({ value }: { value: string | null }) { if (!value) return <span className="text-slate-500">Not available</span>; const text = value.length > 18 ? `${value.slice(0, 10)}…${value.slice(-8)}` : value; return <button type="button" title="Copy full value" onClick={() => void navigator.clipboard?.writeText(value)} className="inline-flex items-center gap-1 font-mono text-xs text-slate-700 hover:text-green-800"><span>{text}</span><Clipboard className="h-3 w-3" /></button>; }
function Detail({ handoff }: { handoff: IntegrityHandoff }) { return <div className="rounded-lg border border-slate-200 bg-white p-4 text-sm"><div className="flex items-center justify-between gap-2"><p className="font-bold uppercase tracking-wide text-slate-900">{handoff.stage.replaceAll('_', ' ')}</p><span className={handoff.status === 'VERIFIED' ? 'text-green-700' : handoff.status === 'WARNING' ? 'text-amber-700' : 'text-red-700'}>{label[handoff.status]}</span></div>{handoff.reason && <p className="mt-2 text-slate-600">{handoff.reason}</p>}<dl className="mt-3 grid gap-2 text-xs sm:grid-cols-2"><div><dt className="text-slate-500">Previous hash</dt><dd><ShortHash value={handoff.previousHash} /></dd></div><div><dt className="text-slate-500">Expected previous hash</dt><dd><ShortHash value={handoff.expectedPreviousHash} /></dd></div><div><dt className="text-slate-500">Recorded current hash</dt><dd><ShortHash value={handoff.currentHash} /></dd></div><div><dt className="text-slate-500">Recalculated hash</dt><dd><ShortHash value={handoff.recalculatedHash} /></dd></div>{handoff.anchor && <><div><dt className="text-slate-500">Network</dt><dd>{handoff.anchor.network}</dd></div><div><dt className="text-slate-500">Transaction</dt><dd><ShortHash value={handoff.anchor.transactionHash} /></dd></div><div><dt className="text-slate-500">Committed hash</dt><dd><ShortHash value={handoff.anchor.committedHash} /></dd></div></>}</dl>{handoff.anchor?.transactionHash && /^0x[\da-fA-F]{64}$/.test(handoff.anchor.transactionHash) && <a href={`https://amoy.polygonscan.com/tx/${handoff.anchor.transactionHash}`} target="_blank" rel="noreferrer" className="mt-3 inline-flex items-center text-xs font-semibold text-purple-700 hover:underline">View transaction on PolygonScan <ExternalLink className="ml-1 h-3 w-3" /></a>}</div>; }

export function IntegrityCard({ integrity, technicalOnly = false }: { integrity: BatchIntegrity; technicalOnly?: boolean }) { return <section className={`rounded-xl border p-5 ${style[integrity.status]}`}><div className="flex items-start gap-3"><Icon status={integrity.status} /><div><p className="text-xs font-bold tracking-[0.16em]">BLOCKCHAIN INTEGRITY</p><h2 className="mt-1 text-xl font-bold">{technicalOnly ? `CHAIN INTEGRITY · ${label[integrity.status]}` : label[integrity.status]}</h2><p className="mt-2 text-sm">{integrity.summary}</p>{integrity.status === 'BROKEN' && <p className="mt-2 text-sm font-medium">Integrity review required. This does not by itself determine food safety.</p>}</div></div><div className="mt-4 flex gap-5 text-sm"><span>{integrity.verifiedHandoffs} verified handoff{integrity.verifiedHandoffs === 1 ? '' : 's'}</span>{integrity.brokenHandoffs > 0 && <span className="font-semibold">{integrity.brokenHandoffs} integrity issue{integrity.brokenHandoffs === 1 ? '' : 's'}</span>}</div><details className="mt-4 rounded-lg border border-slate-200 bg-slate-50 p-3 text-slate-900"><summary className="flex cursor-pointer list-none items-center justify-between font-semibold">Verification details <ChevronDown className="h-4 w-4" /></summary><div className="mt-4 space-y-3">{integrity.handoffs.map((handoff) => <Detail key={handoff.id} handoff={handoff} />)}</div></details></section>; }

export function IntegrityTimelineMark({ status }: { status: IntegrityStatus }) { return <span className={`inline-flex items-center gap-1 text-xs font-semibold ${status === 'VERIFIED' ? 'text-green-700' : status === 'WARNING' ? 'text-amber-700' : 'text-red-700'}`}><Icon status={status} />{status === 'BROKEN' ? 'Integrity issue' : status === 'WARNING' ? 'Verification warning' : 'Verified'}</span>; }
