'use client';

import { useEffect, useState } from 'react';
import { Send, Truck } from 'lucide-react';
import { supabase } from '@/lib/supabaseClient';
import { getAuthenticatedActor } from '@/lib/blockchain';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { PortalShell } from '@/components/portal-shell';

type Batch = { id: string; batch_code: string; crop_name: string; total_weight_kg: number; farm_location: string; batch_handoffs: { assigned_distributor_name: string | null; stage: string }[] };
export default function DistributorPage() {
  const [batches, setBatches] = useState<Batch[]>([]); const [selected, setSelected] = useState<Batch | null>(null); const [retailer, setRetailer] = useState(''); const [message, setMessage] = useState('');
  async function load() { const { data: { user } } = await supabase.auth.getUser(); if (!user) { setMessage('Sign in with a distributor account to view assigned batches.'); return; } const { data: profile } = await supabase.from('profiles').select('full_name').eq('id', user.id).single(); if (!profile) { setMessage('Your distributor profile could not be loaded.'); return; } const { data, error } = await supabase.from('batches').select('id, batch_code, crop_name, total_weight_kg, farm_location, batch_handoffs!inner(assigned_distributor_name, stage), lab_tests!inner(test_status)').eq('status', 'in_transit').eq('is_recalled', false).eq('lab_tests.test_status', 'PASS').eq('batch_handoffs.stage', 'distribution').eq('batch_handoffs.assigned_distributor_name', profile.full_name).order('created_at', { ascending: false }); if (error) setMessage(error.message); else setBatches((data ?? []) as Batch[]); }
  useEffect(() => { const timer = window.setTimeout(() => { void load(); }, 0); return () => window.clearTimeout(timer); }, []);
  async function send(event: React.FormEvent) { event.preventDefault(); if (!selected) return; setMessage(''); try { const user = await getAuthenticatedActor(); const { error: updateError } = await supabase.from('batches').update({ status: 'in_transit' }).eq('id', selected.id); if (updateError) throw updateError; const { error } = await supabase.from('batch_handoffs').insert({ batch_id: selected.id, handler_id: user.id, stage: 'distribution', assigned_retailer_name: retailer, notes: `Sent to ${retailer}` }); if (error) throw error; setMessage(`${selected.batch_code} is now in transit to ${retailer}.`); setSelected(null); setRetailer(''); await load(); } catch (error) { setMessage(error instanceof Error ? error.message : 'Could not send this batch.'); } }
  return <PortalShell title="Distributor logistics" description="Only quality-passed batches are ready to be sent to a retailer." icon={Truck}>{message && <p className="mb-5 rounded-lg border border-green-200 bg-green-50 p-3 text-green-800">{message}</p>}<div className="grid gap-4 md:grid-cols-2">{batches.map((batch) => <Card key={batch.id} className="portal-surface"><CardHeader><CardTitle>{batch.crop_name}</CardTitle><CardDescription className="font-mono">{batch.batch_code}</CardDescription></CardHeader><CardContent><p className="mb-4 text-sm text-slate-600">{batch.total_weight_kg} kg · {batch.farm_location}</p><Button className="portal-action w-full py-4 text-lg font-bold" onClick={() => { setSelected(batch); setMessage(''); }}><Send className="mr-2" />Send to Retailer</Button></CardContent></Card>)}</div>{!batches.length && <Card className="portal-surface"><CardContent className="p-6 text-slate-600">No quality-passed batches are waiting for distribution.</CardContent></Card>}<form onSubmit={send} className={`mt-6 ${selected ? 'block' : 'hidden'}`}><Card className="portal-surface"><CardHeader><CardTitle>Send {selected?.batch_code}</CardTitle></CardHeader><CardContent className="space-y-4"><div><Label htmlFor="retailer">Target retailer name</Label><Input id="retailer" value={retailer} onChange={(event) => setRetailer(event.target.value)} required /></div><Button type="submit" className="portal-action py-4 text-lg font-bold">Confirm dispatch</Button></CardContent></Card></form></PortalShell>;
}
